version: "3.8"

services:
  bus_stop_lookup:
    build:
      context: "./Atomic Service/bus_stop_lookup microservice"
      dockerfile: Dockerfile
    image: bus_stop_lookup:1.0
    container_name: bus_stop_lookup
    ports:
      - "5002:5002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  directions:
    build:
      context: "./Atomic Service/directions microservice"
      dockerfile: Dockerfile
    image: kelvinpcw/directions:1.0
    container_name: directions
    ports:
      - "5001:5001"
    environment:
      - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/directions
    env_file:
      - .env
    networks:
      - app-network

  composite_service:
    build: ./Composite Service/api_gateway
    ports:
      - "5000:5000"
    depends_on:
      - bus_stop_lookup
      - directions
    networks:
      - app-network  # Add this line to connect to the app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: