# version: '3.9'

services:
  app1:
    build: ./app1
    ports:
      - "4243:4243"
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      ENDPOINT_SECRET: ${ENDPOINT_SECRET}
      FLASK_APP: main.py
      FLASK_ENV: development

  app2:
    build: ./app2
    ports:
      - "4242:4242"
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      FLASK_APP: main.py
      FLASK_ENV: development

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: ["listen", "--forward-to", "app1:4243/webhook", "--api-key", "$STRIPE_API_KEY"]
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    volumes:
      - stripe-cli-data:/data
    depends_on:
      - app1
      - app2

volumes:
  stripe-cli-data: